#!/bin/bash
set -e

VERSION=$(bin/_get_version)
PHP_SUBVERSION=${1:-$VERSION}
[ -z $PHP_SUBVERSION ] && exit 1;

bin/_set_perm_dirs

echo phpbrew install $PHP_SUBVERSION +default +apxs2=$(which apxs2) --no-clean
phpbrew install --no-clean $PHP_SUBVERSION +default +apxs2=$(which apxs2) 

bin/_unset_perm_dirs
