#!/bin/bash
set -e

FILE_PHP5_LOAD=/etc/apache2/mods-available/php5.load
PHP_SUBVERSION=5

bin/_set_perm_dirs

source ~/.phpbrew/bashrc

echo phpbrew switch-off
     phpbrew switch-off

if [ -e "$FILE_PHP5_LOAD" ]; then 
  sed -i.bak "s/\(libphp\)[0-9]*\.[0-9]*\.[0-9]*\(.*\)$/\1$PHP_SUBVERSION\2/" "$FILE_PHP5_LOAD"
fi

sudo service apache2 restart
bin/_unset_perm_dirs
